---
title: "Random Forest Model"
output: html_notebook
---

```{r include=FALSE}
library(varSelRF)
set.seed(644685)
library(openxlsx)
library(stringr)
```

##Using *varSelRF* package for variable selection using random forest

https://cran.r-project.org/web/packages/varSelRF/varSelRF.pdf

I normalized the pre-filtered gene counts of the 92 AIH and healthy patients (no liver transplants, no outliers and no complex cases) using cpm() function of EdgeR, log = TRUE.



```{r}
# load in genecounts and metadata
genecounts_rf <- genecountspc_filt
metadata_rf <- metadata_filt

# normalize gene counts
genecounts_filt_cpm <- cpm(genecountspc_filt, log = TRUE)

# set up the column of interest, remove empty levels
metadata_rf$factors <- droplevels.factor(metadata_filt$case_hl_du)

#declare the factors for random forest model
RF_factors <- metadata_rf$factors

#initialize data frame and standard deviation
RF_results <-data.frame(standarddev = integer(), num_genes = integer(), genes = character())
RF_results <- rbind(RF_results, c(stddev, num.genes, paste(unlist(genes), collapse=', ')))

stddev = 0.5

num.genes = 0

while (num.genes < 50) {
#run random forest
varselRF.AIH <- varSelRF(t(genecounts_filt_cpm), as.factor(RF_factors), c.sd = stddev, mtryFactor = 1, ntree = 5000, ntreeIterat = 2000, vars.drop.num = NULL, vars.drop.frac = 0.2, whole.range = FALSE, recompute.var.imp = FALSE, verbose = TRUE, returnFirstForest = TRUE, fitted.rf = NULL, keep.forest = TRUE)

#store data into data frame
genes = genemap[match(varselRF.AIH$selected.vars, genemap$ensembl_gene_id),]$hgnc
num.genes = varselRF.AIH$best.model.nvars
RF_results <- rbind(RF_results, c(stddev, num.genes, paste(unlist(genes), collapse=', ')))
colnames(RF_results) <- c("stddev","num.genes","genes")

print(paste("Standard deviation is", stddev))
print(paste("Number of genes is",num.genes))

#divide standard deviation in half
stddev = stddev - 0.25

}
?rbind

colnames(RF_results) <- c("stddev","num.genes","genes")

```

